### ISSUE TITLE
Impossible de partager des gros fichiers

### ISSUE THREAD

**Issue by maniackcrudelis** [Kloadut/owncloud_ynh#15]
Bonjour,

En raison du paramètre 'request_terminate_timeout = 120s' dans le fichier owncloud.conf pour php5-fpm, il est impossible de partager des gros fichiers, le téléchargement échoue avant son terme.

<code>[20-Aug-2014 14:28:15] WARNING: [pool owncloud] child 13430 exited on signal 15 (SIGTERM) after 1205.769667 seconds from start</code>

Dans mon log, j'avais déjà augmenté cette valeur à 1200s.
Augmenter cette valeur reste toutefois à mon avis une solution provisoire, puisque j'upload déjà dans le cas présent à 6.2Mb

**Comment by julienmalik** [comment]
A voir ce qu'on a fait sur Jirafeau...

**Comment by julienmalik** [comment]
https://github.com/julienmalik/jirafeau_ynh/commit/8c7c802e92d1f2036e28615a94505aac502ec304
