### ISSUE TITLE
Webdav authentication problem with accented characters (at least "é")

### ISSUE THREAD

**Issue by Zerwan** [Kloadut/owncloud_ynh#21]
Webdav auth seems not to work when the yunohost password contains characters such as "é".

Here is the situation I had:

- I have yunohost up to date with owncloup app up to date
- My yunohost password was a random series of alphanumeric characters, and everything was working fine: web client, desktop sync client, webdav, etc.
- Then I changed my yunohost password to a new one, with both alphanum and some "é" characters
- With this new password, all my yunohost apps worked well, even owncloud with the web client and the desktop sync clien. BUT owncloud webdav access (https://truc.org/owncloud/remote.php/webdav/) stopped working: impossible to authenticate, whichever the webdav client (firefox, nautilus, keepass2android, etc)
- Finally I changed my yunohost password to replace the "é" by "e" and webdav worked again

**Comment by Kloadut** [comment]
Fixed as of 1a3cd31c582fe09d1eead605614648eb44409641

The default PHP charset was not set to UTF-8
https://github.com/Kloadut/owncloud_ynh/blob/master/conf/php-fpm.conf#L244
