### ISSUE TITLE
Install script does not allow root domain install

### ISSUE THREAD

**Issue by ZeHiro** [Kloadut/owncloud_ynh#26]
Hello,

I have tried to install owncloud using moulinette (and web interface) and, the current script does not allow to set the location at the root of the domain, which does not allow to use subdomains. Here is what I set : 
- domain : owncloud.mydomain.tld
- path : / 

the generated owncloud.conf file is as following : 

location  {
       alias /var/www/owncloud/

I guess the problem is on line 59 : 

sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/owncloud.conf

A "/" is missing after $path

Thanks

**Comment by novakin** [comment]
Made push request,

**Comment by Kloadut** [comment]
Fixed as of a60ec55807e88d5ad8f2a6ea05d8a61d2636c0e9
