### ISSUE TITLE
Owncloud 8 got broken before the update

### ISSUE THREAD

**Issue by Eynix** [Kloadut/owncloud_ynh#32]
Hi,

  I did an update of owncloud this morning with moulinette : 

- the web UI is broken (see http://pastebin.com/qj12HynB, IP has been changed). It seems that owncloud doesn't find some JS files.

- other features work as expected (sync, android app,...)

note: the update (yunohost app upgrade) triggered an error regarding the post-install scripts. As I tried to access owncloud it get into maintenance mode and was stucked in it. I did "./occ upgrade" in /var/www/owncloud, now owncloud isn't stuck in maintenance mode anymore but display an empty page and firebug telling me "NetworkError: 500 Internal Server Error - https://monserv/owncloud/index.php/apps/files/". Maybe this is helping.

**Comment by zamentur** [comment]
His server was a yunohost jessie with with php 5.6.
I think the package was not tested with this conf.

**Comment by Kloadut** [comment]
It is now
