### ISSUE TITLE
Please update to owncloud 8.1

### ISSUE THREAD

**Issue by mat-mo** [Kloadut/owncloud_ynh#35]
Latest stable release.

**Comment by zamentur** [comment]
I start an update of the package

**Comment by zamentur** [comment]
https://github.com/zamentur/owncloud_ynh

**Comment by mat-mo** [comment]
Can you please create a pull request ?

**Comment by zamentur** [comment]
I wait that people test on jessy before. I have just tested it on wheezy

**Comment by mat-mo** [comment]
This can be closed now.
