### ISSUE TITLE
Set home folder permissions for existing users

### ISSUE THREAD

**Issue by jeromelebleu** [Kloadut/owncloud_ynh#36]
If a user already exists at ownCloud installation, its home folder's permissions are not updated to be properly accessible in ownCloud - i.e. read/write access for the *owncloud* group.

The users list should be parsed and the hook `post_user_create` should be executed for each of them.

**Comment by zamentur** [comment]
It seems it was already done in install scripts, I added it in upgrade:
https://github.com/zamentur/owncloud_ynh/blob/master/scripts/install#L93
