### ISSUE TITLE
upgrade 8.2.0 fail

### ISSUE THREAD

**Issue by sethobscur** [Kloadut/owncloud_ynh#53]
Hello, 

I tried to upgrade my owncloud version, using "yunohost app upgrade" but it failed. Now the web interface is in maintenance mode, and when I desactivate this mode, I can not upgrade as I have the following output :

>ownCloud sera mis à jour vers la version 8.2.0.
>Les applications suivantes seront mises à jour:
>
>    Activity (activity)
>    Files (files)
>    External storage support (files_external)
>    Share Files (files_sharing)
>    Text Editor (files_texteditor)
>    Deleted files (files_trashbin)
>    Versions (files_versions)
>    Gallery (gallery)
>    Provisioning API (provisioning_api)
>    Updater (updater)
>    LDAP user and group backend (user_ldap)
>
>Ces applications incompatibles ont été désactivées:
>
>    Calendar (calendar)
>    Contacts (contacts)

and when I start the update :

> Exception: Updates between multiple major versions and downgrades are unsupported.
> The update was unsuccessful.

I link the output of yunohost app upgrade, if this can help.
[output.txt](https://github.com/Kloadut/owncloud_ynh/files/94785/output.txt)

**Comment by zamentur** [comment]
A method to fix your problem :
cd
wget https://github.com/Kloadut/owncloud_ynh/archive/6b87f7e973dd1bb6b56e13a4aef3a466a0eeac6c.tar.gz
mv 6b87f7e973dd1bb6b56e13a4aef3a466a0eeac6c.tar.gz owncloud7.tar.gz
sudo yunohost app upgrade owncloud -f owncloud7.tar.gz

Next
sudo yunohost app upgrade owncloud
OR
sudo yunohost app upgrade owncloud -u https://github.com/Kloadut/owncloud_ynh

**Comment by sethobscur** [comment]
Thanks, it works !
