### ISSUE TITLE
Update to 8.2.1

### ISSUE THREAD

**Issue by M0dM** [Kloadut/owncloud_ynh#54]
I need this issue fixed to share pictures between me and my friends.

https://github.com/owncloud/core/pull/19956
https://github.com/owncloud/core/pull/19956/files

Did you plan to update owncloud version soon ?

**Comment by mat-mo** [comment]
Version 9 is out already.

**Comment by M0dM** [comment]
Perfect, thanks.
So it's time to close this issue ;)
