### ISSUE TITLE
update to owncloud 9 please

### ISSUE THREAD

**Issue by mat-mo** [Kloadut/owncloud_ynh#58]
OC 9 is out, please update this package to provide it.

**Comment by taziden** [comment]
@mat-mo Hello, Thank you.

**Comment by stevenroose** [comment]
@Kloadut What has to happen to upgrade to v9? 

I'm trying to setup a test environment so that I can try to update the package.

**Comment by Psycojoker** [comment]
You should look at @jeromelebleu work for 9.0. He is looking for testers.

https://github.com/jeromelebleu/owncloud_ynh

**Comment by jeromelebleu** [comment]
@stevenroose, as @Psycojoker said, feel fry to try this new package which will replace this one soon - and by the way moves to YunoHost-Apps as soon as it's tested and ready. Please note that you will need the current testing version of YunoHost (>=2.3.12), and [here](https://github.com/jeromelebleu/owncloud_ynh#installation) is some doc about how to install this app. Thanks in advance for testing and giving feedbacks!

**Comment by jeromelebleu** [comment]
Done in this [new repository](https://github.com/YunoHost-Apps/owncloud_ynh).
